[2023-02-15T01:17:27.628+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_dag.download_data manual__2023-02-15T01:10:59.172626+00:00 [queued]>
[2023-02-15T01:17:27.644+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: my_dag.download_data manual__2023-02-15T01:10:59.172626+00:00 [queued]>
[2023-02-15T01:17:27.644+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:17:27.645+0000] {taskinstance.py:1280} INFO - Starting attempt 3 of 3
[2023-02-15T01:17:27.645+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T01:17:27.678+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): download_data> on 2023-02-15 01:10:59.172626+00:00
[2023-02-15T01:17:27.686+0000] {standard_task_runner.py:55} INFO - Started process 1182 to run task
[2023-02-15T01:17:27.690+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'download_data', 'manual__2023-02-15T01:10:59.172626+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/firts_dag.py', '--cfg-path', '/tmp/tmpf0b1xwte']
[2023-02-15T01:17:27.691+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask download_data
[2023-02-15T01:17:27.786+0000] {task_command.py:388} INFO - Running <TaskInstance: my_dag.download_data manual__2023-02-15T01:10:59.172626+00:00 [running]> on host ca65f84028ad
[2023-02-15T01:17:27.916+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T01:10:59.172626+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T01:10:59.172626+00:00
[2023-02-15T01:17:27.917+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T01:17:27.918+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'poetry shell && scrapy crawl linkedin_jobs -O json.json']
[2023-02-15T01:17:27.938+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T01:17:27.941+0000] {subprocess.py:93} INFO - /bin/bash: line 1: poetry: command not found
[2023-02-15T01:17:27.942+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-02-15T01:17:27.958+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-02-15T01:17:27.964+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=my_dag, task_id=download_data, execution_date=20230215T011059, start_date=20230215T011727, end_date=20230215T011727
[2023-02-15T01:17:27.989+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task download_data (Bash command failed. The command returned a non-zero exit code 127.; 1182)
[2023-02-15T01:17:28.022+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-15T01:17:28.049+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
